name: CI

on:
  push:
    branches: 
      - "*"
    tags:
      - "*"
  pull_request:
    branches: 
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install Dependencies
        run: bun install

      - name: Check with Biome
        run: bun check

      - name: Build
        run: |
          bun builder

      - name: Test
        run: |
          bun test download --coverage
          bun test extract --coverage
          bun test analyze --coverage
          bun test normalize --coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'av-mpm-${{ github.sha }}-${{ matrix.os }}'
          path: 'dist/*'
        continue-on-error: true


